Repository 4S1JIN/s1jin-delivery, pull requests merged in 2025-02, with the labels that each got.

#3 가게 관리 기능 개발
  build.gradle
  src/main/java/com/fourseason/delivery/domain/member/repository/MemberRepository.java
  src/main/java/com/fourseason/delivery/domain/shop/controller/ShopController.java
  src/main/java/com/fourseason/delivery/domain/shop/dto/request/CreateShopRequestDto.java
  src/main/java/com/fourseason/delivery/domain/shop/dto/request/UpdateShopRequestDto.java
  src/main/java/com/fourseason/delivery/domain/shop/dto/response/ShopResponseDto.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/Category.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/Shop.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/ShopImage.java
  src/main/java/com/fourseason/delivery/domain/shop/exception/ShopErrorCode.java
  src/main/java/com/fourseason/delivery/domain/shop/repository/CategoryRepository.java
  src/main/java/com/fourseason/delivery/domain/shop/repository/ShopImageRepository.java
  src/main/java/com/fourseason/delivery/domain/shop/repository/ShopRepository.java
  src/main/java/com/fourseason/delivery/domain/shop/repository/ShopRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/shop/service/ShopService.java
  src/main/java/com/fourseason/delivery/global/config/QuerydslConfig.java
  src/main/java/com/fourseason/delivery/global/dto/PageRequestDto.java
  src/main/java/com/fourseason/delivery/global/dto/PageResponseDto.java
  src/main/java/com/fourseason/delivery/global/entity/BaseTimeEntity.java
  src/main/resources/application.yml
Labels: enhancement

#4 메뉴 관리 기능 개발
  src/main/java/com/fourseason/delivery/domain/menu/controller/MenuController.java
  src/main/java/com/fourseason/delivery/domain/menu/dto/request/CreateMenuRequestDto.java
  src/main/java/com/fourseason/delivery/domain/menu/dto/request/UpdateMenuRequestDto.java
  src/main/java/com/fourseason/delivery/domain/menu/dto/response/MenuResponseDto.java
  src/main/java/com/fourseason/delivery/domain/menu/entity/Menu.java
  src/main/java/com/fourseason/delivery/domain/menu/entity/MenuImage.java
  src/main/java/com/fourseason/delivery/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuImageRepository.java
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/menu/service/MenuService.java
  src/main/java/com/fourseason/delivery/domain/shop/controller/ShopController.java
  src/main/java/com/fourseason/delivery/domain/shop/repository/ShopRepositoryCustom.java
  src/main/java/com/fourseason/delivery/global/dto/PageRequestDto.java
Labels: enhancement

#10 주문 요청 API 구현
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/fourseason/delivery/domain/order/controller/OrderCustomerController.java
  src/main/java/com/fourseason/delivery/domain/order/dto/request/CreateOrderRequestDto.java
  src/main/java/com/fourseason/delivery/domain/order/entity/Order.java
  src/main/java/com/fourseason/delivery/domain/order/entity/OrderMenu.java
  src/main/java/com/fourseason/delivery/domain/order/entity/OrderStatus.java
  src/main/java/com/fourseason/delivery/domain/order/exception/OrderErrorCode.java
  src/main/java/com/fourseason/delivery/domain/order/repository/OrderMenuRepository.java
  src/main/java/com/fourseason/delivery/domain/order/repository/OrderRepository.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderCustomerService.java
  src/main/java/com/fourseason/delivery/global/exception/CustomException.java
  src/test/java/com/fourseason/delivery/domain/order/service/OrderCustomerServiceTest.java
Labels: enhancement

#14 가게 Owner 주문 수락 API 구현
  http/order.http
  src/main/java/com/fourseason/delivery/domain/order/controller/OrderOwnerController.java
  src/main/java/com/fourseason/delivery/domain/order/dto/request/CreateOrderRequestDto.java
  src/main/java/com/fourseason/delivery/domain/order/entity/Order.java
  src/main/java/com/fourseason/delivery/domain/order/exception/OrderErrorCode.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderOwnerService.java
  src/test/java/com/fourseason/delivery/domain/order/service/OrderOwnerServiceTest.java
Labels: enhancement

#19 feat: 이미지 업로드 기능 추가
  build.gradle
  src/main/java/com/fourseason/delivery/domain/image/enums/S3Folder.java
  src/main/java/com/fourseason/delivery/domain/image/exception/ImageErrorCode.java
  src/main/java/com/fourseason/delivery/domain/image/service/FileService.java
  src/main/java/com/fourseason/delivery/domain/image/service/S3Service.java
  src/main/java/com/fourseason/delivery/domain/menu/controller/MenuController.java
  src/main/java/com/fourseason/delivery/domain/menu/dto/request/CreateMenuRequestDto.java
  src/main/java/com/fourseason/delivery/domain/menu/entity/Menu.java
  src/main/java/com/fourseason/delivery/domain/menu/entity/MenuImage.java
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/menu/service/MenuService.java
  src/main/java/com/fourseason/delivery/domain/shop/controller/ShopController.java
  src/main/java/com/fourseason/delivery/domain/shop/dto/request/CreateShopRequestDto.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/ShopImage.java
  src/main/java/com/fourseason/delivery/domain/shop/repository/ShopRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/shop/service/ShopService.java
  src/main/java/com/fourseason/delivery/global/auth/filter/JwtCheckFilter.java
  src/main/java/com/fourseason/delivery/global/config/QuerydslConfig.java
  src/main/java/com/fourseason/delivery/global/config/S3Config.java
  src/main/resources/application.yml
Labels: enhancement

#18 고객 주문 조회 API
  http/order.http
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/fourseason/delivery/domain/order/controller/OrderCustomerController.java
  src/main/java/com/fourseason/delivery/domain/order/dto/response/OrderDetailResponseDto.java
  src/main/java/com/fourseason/delivery/domain/order/dto/response/OrderSummaryResponseDto.java
  src/main/java/com/fourseason/delivery/domain/order/entity/Order.java
  src/main/java/com/fourseason/delivery/domain/order/entity/OrderMenu.java
  src/main/java/com/fourseason/delivery/domain/order/entity/OrderType.java
  src/main/java/com/fourseason/delivery/domain/order/exception/OrderErrorCode.java
  src/main/java/com/fourseason/delivery/domain/order/repository/OrderRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderCustomerService.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderOwnerService.java
  src/test/java/com/fourseason/delivery/domain/order/service/OrderCustomerServiceTest.java
  src/test/java/com/fourseason/delivery/domain/order/service/OrderOwnerServiceTest.java
  src/test/java/com/fourseason/delivery/fixture/MemberFixture.java
  src/test/java/com/fourseason/delivery/fixture/MenuFixture.java
  src/test/java/com/fourseason/delivery/fixture/OrderFixture.java
  src/test/java/com/fourseason/delivery/fixture/OrderMenuFixture.java
  src/test/java/com/fourseason/delivery/fixture/ShopFixture.java
Labels: enhancement

#29 고객 주문 취소, 삭제 API 구현
  http/order.http
  src/main/java/com/fourseason/delivery/domain/order/controller/OrderCustomerController.java
  src/main/java/com/fourseason/delivery/domain/order/entity/Order.java
  src/main/java/com/fourseason/delivery/domain/order/exception/OrderErrorCode.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderCustomerService.java
  src/test/java/com/fourseason/delivery/domain/order/service/OrderCustomerServiceTest.java
  src/test/java/com/fourseason/delivery/fixture/OrderFixture.java
Labels: enhancement

#31 점주 주문 접수, 취소 API 구현
  http/order.http
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuRepository.java
  src/main/java/com/fourseason/delivery/domain/order/controller/OrderOwnerController.java
  src/main/java/com/fourseason/delivery/domain/order/dto/request/OwnerCreateOrderRequestDto.java
  src/main/java/com/fourseason/delivery/domain/order/dto/response/OrderSummaryResponseDto.java
  src/main/java/com/fourseason/delivery/domain/order/dto/response/OwnerOrderDetailResponseDto.java
  src/main/java/com/fourseason/delivery/domain/order/dto/response/OwnerOrderSummaryResponseDto.java
  src/main/java/com/fourseason/delivery/domain/order/entity/Order.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderCustomerService.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderOwnerService.java
  src/test/java/com/fourseason/delivery/domain/order/service/OrderCustomerServiceTest.java
  src/test/java/com/fourseason/delivery/domain/order/service/OrderOwnerServiceTest.java
Labels: enhancement

#38 release 설정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  appspec.yml
  scripts/start-server.sh
  src/main/resources/application-local.yml
  src/test/java/com/fourseason/delivery/DeliveryApplicationTests.java
  src/test/java/com/fourseason/delivery/global/auth/JwtUtilTest.java
Labels: enhancement

#45 MEMBER ERRORCODE 충돌 부분 / 테스트 코드 수정
  src/main/java/com/fourseason/delivery/domain/member/exception/MemberErrorCode.java
  src/main/java/com/fourseason/delivery/global/auth/controller/AuthController.java
  src/main/java/com/fourseason/delivery/global/auth/service/AuthService.java
  src/test/java/com/fourseason/delivery/AuthTest.java
  src/test/java/com/fourseason/delivery/global/auth/JwtUtilTest.java
  src/test/java/com/fourseason/delivery/global/auth/controller/AuthControllerTest.java
Labels: test

#40 Feature/#7 payment
  build.gradle
  src/main/java/com/fourseason/delivery/TestInitializer.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/PaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/PaymentHtmlController.java
  src/main/java/com/fourseason/delivery/domain/payment/dto/external/ExternalCancelPaymentDto.java
  src/main/java/com/fourseason/delivery/domain/payment/dto/external/ExternalPaymentDto.java
  src/main/java/com/fourseason/delivery/domain/payment/dto/request/CancelPaymentRequestDto.java
  src/main/java/com/fourseason/delivery/domain/payment/dto/request/CreatePaymentRequestDto.java
  src/main/java/com/fourseason/delivery/domain/payment/dto/response/PaymentResponseDto.java
  src/main/java/com/fourseason/delivery/domain/payment/entity/Payment.java
  src/main/java/com/fourseason/delivery/domain/payment/exception/CustomRestClientException.java
  src/main/java/com/fourseason/delivery/domain/payment/exception/PaymentErrorCode.java
  src/main/java/com/fourseason/delivery/domain/payment/repository/PaymentRepository.java
  src/main/java/com/fourseason/delivery/domain/payment/repository/PaymentRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentExternalService.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentService.java
  src/main/java/com/fourseason/delivery/global/auth/filter/JwtCheckFilter.java
  src/main/java/com/fourseason/delivery/global/config/MvcConfiguration.java
  src/main/java/com/fourseason/delivery/global/dto/PageRequestDto.java
  src/main/java/com/fourseason/delivery/global/exception/GlobalExceptionHandler.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/checkout.html
  src/main/resources/templates/fail.html
  src/main/resources/templates/success.html
  src/test/java/com/fourseason/delivery/domain/payment/service/PaymentServiceTest.java
Labels: enhancement

#43 가게 관리 리팩토링 및 테스트 코드 작성
  src/main/java/com/fourseason/delivery/domain/menu/controller/MenuController.java
  src/main/java/com/fourseason/delivery/domain/menu/entity/MenuImage.java
  src/main/java/com/fourseason/delivery/domain/shop/controller/ShopController.java
  src/main/java/com/fourseason/delivery/domain/shop/dto/request/CreateShopRequestDto.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/Category.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/Shop.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/ShopImage.java
  src/main/java/com/fourseason/delivery/domain/shop/service/ShopService.java
  src/main/java/com/fourseason/delivery/global/config/WebConfig.java
  src/main/java/com/fourseason/delivery/global/dto/PageRequestDto.java
  src/main/java/com/fourseason/delivery/global/resolver/PageSize.java
  src/main/java/com/fourseason/delivery/global/resolver/PageSizeArgumentResolver.java
  src/test/java/com/fourseason/delivery/domain/shop/controller/ShopControllerTest.java
  src/test/java/com/fourseason/delivery/domain/shop/service/ShopServiceTest.java
  src/test/java/com/fourseason/delivery/global/annotation/WithCustomMockUser.java
  src/test/java/com/fourseason/delivery/global/annotation/WithCustomMockUserSecurityContextFactory.java
Labels: test

#46 AI 기반 메뉴 추천 기능 추가
  src/main/java/com/fourseason/delivery/domain/ai/controller/GeminiController.java
  src/main/java/com/fourseason/delivery/domain/ai/entity/AiResponse.java
  src/main/java/com/fourseason/delivery/domain/ai/repository/AiResponseRepository.java
  src/main/java/com/fourseason/delivery/domain/ai/service/GeminiService.java
  src/main/resources/application-local.yml
Labels: enhancement

#44 JWT 토큰 검증 필터에서 Swagger 경로 예외 처리 추가
  src/main/java/com/fourseason/delivery/global/auth/filter/JwtCheckFilter.java
Labels: documentation

#50 오타 수정
  src/main/java/com/fourseason/delivery/global/auth/filter/JwtCheckFilter.java
Labels: hotfix

#51 #7 hotfix: memberRepository 수정사항 반영
  src/main/java/com/fourseason/delivery/TestInitializer.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/PaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentExternalService.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentService.java
Labels: hotfix

#54 빌드 오류 수정
  src/main/java/com/fourseason/delivery/domain/member/MemberErrorCode.java
  src/main/java/com/fourseason/delivery/domain/member/exception/MemberErrorCode.java
  src/main/java/com/fourseason/delivery/domain/order/service/OrderCustomerService.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentExternalService.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentService.java
  src/main/java/com/fourseason/delivery/domain/shop/service/ShopService.java
  src/test/java/com/fourseason/delivery/domain/shop/service/ShopServiceTest.java
  src/test/java/com/fourseason/delivery/global/annotation/WithCustomMockUser.java
Labels: hotfix

#55 hotfix: 테스트 빌드 오류 수정
  src/test/java/com/fourseason/delivery/global/annotation/WithCustomMockUserSecurityContextFactory.java
Labels: hotfix

#61 Auth Test 오류 수정
  build.gradle
  src/test/java/com/fourseason/delivery/AuthTest.java
Labels: bug

#64 Exception 전달 방식 수정
  src/main/java/com/fourseason/delivery/global/auth/filter/JwtCheckFilter.java
  src/test/java/com/fourseason/delivery/AuthTest.java
Labels: enhancement

#58 Feature/#42 payment role
  src/main/java/com/fourseason/delivery/domain/payment/controller/AdminPaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/CustomerPaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/OwnerPaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/PaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/exception/PaymentErrorCode.java
  src/main/java/com/fourseason/delivery/domain/payment/repository/PaymentRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentExternalService.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentService.java
  src/main/java/com/fourseason/delivery/domain/shop/entity/Category.java
  src/main/resources/templates/success.html
Labels: enhancement

#60 Feature/#59 payment compensate
  src/main/java/com/fourseason/delivery/domain/payment/controller/AdminPaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/CustomerPaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/controller/OwnerPaymentController.java
  src/main/java/com/fourseason/delivery/domain/payment/entity/Payment.java
  src/main/java/com/fourseason/delivery/domain/payment/exception/CustomRestClientException.java
  src/main/java/com/fourseason/delivery/domain/payment/exception/PaymentErrorCode.java
  src/main/java/com/fourseason/delivery/domain/payment/exception/RestErrorResponse.java
  src/main/java/com/fourseason/delivery/domain/payment/repository/PaymentRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentCompensatingService.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentExternalService.java
  src/main/java/com/fourseason/delivery/domain/payment/service/PaymentService.java
  src/main/java/com/fourseason/delivery/global/config/AsyncConfig.java
  src/main/java/com/fourseason/delivery/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#63 menu 업데이트 시 image 기능 추가
  src/main/java/com/fourseason/delivery/domain/menu/controller/MenuController.java
  src/main/java/com/fourseason/delivery/domain/menu/dto/request/UpdateMenuRequestDto.java
  src/main/java/com/fourseason/delivery/domain/menu/exception/MenuErrorCode.java
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuImageRepository.java
  src/main/java/com/fourseason/delivery/domain/menu/repository/MenuRepositoryCustom.java
  src/main/java/com/fourseason/delivery/domain/menu/service/MenuService.java
  src/main/java/com/fourseason/delivery/domain/shop/repository/ShopRepositoryCustom.java
Labels: enhancement

#65 리뷰 이미지 업데이트 기능 수정
  src/main/java/com/fourseason/delivery/domain/review/controller/ReviewController.java
  src/main/java/com/fourseason/delivery/domain/review/dto/request/ReviewUpdateRequestDto.java
  src/main/java/com/fourseason/delivery/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/fourseason/delivery/domain/review/entity/Review.java
  src/main/java/com/fourseason/delivery/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/fourseason/delivery/domain/review/repository/ReviewImageRepository.java
  src/main/java/com/fourseason/delivery/domain/review/service/ReviewService.java
Labels: enhancement
